ScholarRepo/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('signup/' ,views.signup, name='signup'),
    path('home/', views.home, name = 'home'),
    path('signin/', views.signin, name= 'signin'),
    path('upload/', views.upload, name='upload'),
    path('find/', views.find, name='find'),
    path('project/<int:id>/', views.project_details, name = 'project-details'),
    path('settings/general', views.settings_general, name = 'settings'),
    path('profile/<int:id>/', views.profile, name = 'profile'),
    path('like_project/<int:id>/', views.like_project, name = 'like'),
    path('signout/', views.signout, name='signout'),
    path('settings/projects/', views.project_settings, name = 'project-settings'),
    path('delete-project/<int:id>/', views.delete_project, name='delete-project'),
    path('profile/', views.my_profile, name='profile'),
    path('delete-comment/<int:id>/', views.delete_comment, name='delete-comment'),
    path('delete-reply/<int:id>/', views.delete_reply, name='delete-reply'),
    path('settings/', views.settings_general, name = 'settings'),
    path('settings/legal', views.settings_legal, name = 'legal'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Role(models.Model):
    name = models.CharField ('User Role', max_length=8)
    permisions = models.CharField()

    def __str__(self):
        return self.name

class User(AbstractUser):
    email = models.EmailField(unique=True)
    role= models.ForeignKey(Role, on_delete=models.CASCADE, null=True, blank= True)
    created_at = models.DateTimeField(auto_now_add=True)
    github = models.TextField(null=True, blank=True)
    linkedin = models.TextField(null=True, blank=True)
    instagram = models.TextField(null=True, blank=True)
    link = models.TextField(null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    profile_pic = models.ImageField(upload_to='profile_pic/', null=True, blank=True, default='profile_pic/logo.png')
    
    def __str__(self):
        return self.username
    
class Category(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name

class Project(models.Model):
    title = models.CharField()
    description = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    cover_image = models.ImageField(upload_to='project_images/')
    demo_video = models.FileField( blank=True, null=True, upload_to='demo_videos/', default='demo_videos/default.mp4')
    github_link = models.URLField()
    live_link = models.URLField()
    uploaded_by = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    assigned_lecturer = models.CharField( max_length=100, blank=True)
    likes = models.ManyToManyField(User, related_name="likes", blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    #likes counter
    def number_of_likes(self):
        return self.likes.count()
    
    def __str__(self):
        return self.title
    
class Comment(models.Model):
    user= models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='comments')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user
    
class Reply(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user

templates/find.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/jpg" href="{% static 'favicon.jpg' %}">
    <link rel="stylesheet" href="{% static 'find.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">
    <title>ScholarRepo | Find</title>
</head>
<body>
    <header>
        <img src="{% static 'header.png' %}" alt="ScholarRepo" class="img-header">
        <nav>
            <ul>
                <a href="{% url 'home' %}"><img src="{% static 'home.png' %}" alt="home" width="25px" height="25px" class="nav-img">Home</a>
                <a href="{% url 'find' %}" class="find"><img src="{% static 'find.png' %}" alt="find" width="25px" height="25px">Find</a>
                <a href="{% url 'upload' %}"><img src="{% static 'upload.png' %}" alt="upload" width="25px" height="25px" class="nav-img">Upload</a>
                <a href="#"><img src="{% static 'notification.png' %}" alt="alerts" width="25px" height="25px" class="nav-img">Alerts</a>
                <details>
                    <summary>
                        <img src="{% static 'user.png'%}" alt="user" width="25px" height="25px" class="nav-img">Account
                    </summary>
                    <div class="account">
                        <a href="{% url 'profile' %}"><img src="{% static 'profile.png' %}" alt="signin" width="25px" height="25px">Profile</a>
                        <a href="{% url 'settings'%}"><img src="{% static 'settings.png' %}" alt="signin" width="25px" height="25px">Settings</a>
                        <a href="{% url 'signout' %}"><img src="{% static 'signin.png' %}" alt="signin" width="25px" height="25px"> Sign Out</a>
                    </div>
                </details>
            </ul>
        </nav>
    </header>
    <main>
        <section>
            <div class="search">
            <form action="{% url 'find' %}" method="POST">
                {% csrf_token %}

                {% if search %}
                    <label for="search"><h1>{{search | capfirst}}</h1></label>
                {% else %}
                    <label for="search"><h1>Search for Project</h1></label>
                {% endif %}
                <input type="search" placeholder="🔍 Search" id="search" name="search">
                <button type="submit">search</button>
            </form>
            <div class="sort-filter">
                <!-- <select name="sort" id="sort">
                    <option value="" selected><img src="{% static 'sort.png' %}" alt="sort" width="25" height="25">Sort</option>
                    <option value="A to Z">A to Z</option>
                    <option value="Z to A">Z to A</option>
                    <option value="Z to A">Recent</option>
                    <option value="Z to A">Oldest</option>
                </select> -->

                <select name="filter" id="filter">
                    <option value="" selected><img src="{% static 'filter.png' %}" alt="filter" width="25" height="25">Filter</option>
                    <option value="A to Z">Category</option>
                    <option value="Z to A">Title</option>
                    <option value="Z to A">Lecturer</option>
                    <option value="Z to A">Owner</option>
                </select>
            </div>
        </div>
        </section>
        <section class="result">
            {% if search %}
            {% for project in projects %}
                <a href="{% url 'project-details' project.id %}">
                    <article>
                        <figure>
                            <img src="{{ project.cover_image.url }}" alt="Project cover">
                        </figure>
                        <figcaption>
                            <div class="description">
                                <h3>{{project.category}}</h3>
                                <h4>{{project.title}}</h4>
                            </div>
                            <div class="user-project">
                                <img src="{% static 'user.png'%}" alt="user" width="30px" height="30px">
                                <h6>{{project.uploaded_by}}</h6>
                            </div>
                        </figcaption>
                    </article>
                </a>
            {% endfor %}
            {% endif %}
        </section>
    </main>

    <footer>
        <div class="scholarRepo footer">
            <img src="{% static 'logo.png' %}" alt="logo" class="nav-img" width="120" height="120">
        </div>
        <div class="footer">
            <ul>
                <h5>Socials</h5>
                <a href="https://www.x.com/">X</a>
                <a href="https://www.instagram.com/">Instagram</a>
                <a href="https://www.facebook.com/">Facebook</a>
                <a href="https://www.linkedin.com/">LinkedIn</a>
            </ul>
        </div>
        <div class="footer">
            <ul>
                <h5>Explore</h5>
                <a href="#">Alerts</a>
                <a href="#">My Account</a>
                <a href="#">Find Repo</a>
                <a href="{% url 'upload' %}">Upload Project</a>
            </ul>
        </div>
        <div class="footer">
            <ul>
                <h5>Developers</h5>
                <a href="https://sbk-socials.vercel.app/"><em>SBKmadeIT</em></a>
                <a href="https://www.facebook.com/">Facebook</a>
                <a href="https://www.snapchat.com/">Snapchat</a>
                <a href="https://www.instagram.com/">Instagram</a>
            </ul>
        </div>
        <div class="footer">
            <ul>
                <h5>Legal</h5>
                <a href="#">Terms</a>
                <a href="#">Privacy</a>
                <a href="#">Cookies</a>
                <a href="">Licenses</a>
            </ul>
        </div>
    </footer>
    <p> &copy; <script> document.write(new Date().getFullYear()) </script> SBKmadeIT | All Rights Reserved</p>
</body>
</html>

templates/project-details.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/jpg" href="{% static 'favicon.jpg' %}">
    <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'project-details.css' %}">
    <title>ScholarRepo | Project Details</title>
</head>
<body>
    <header>
        <img src="{% static 'header.png' %}" alt="ScholarRepo" class="img-header">
        <nav>
            <ul>
                <a href="{% url 'home' %}" class="home"><img src="{% static 'home.png' %}" alt="home" width="25px" height="25px" class="nav-img">Home</a>
                <a href="{% url 'find' %}"><img src="{% static 'find.png' %}" alt="find" width="25px" height="25px" class="nav-img">Find</a>
                <a href="{% url 'upload' %}"><img src="{% static 'upload.png' %}" alt="upload" width="25px" height="25px" class="nav-img">Upload</a>
                <a href="#"><img src="{% static 'notification.png' %}" alt="alerts" width="25px" height="25px" class="nav-img">Alerts</a>
                <details>
                    <summary>
                        <img src="{% static 'user.png'%}" alt="user" width="25px" height="25px" class="nav-img">Account
                    </summary>
                    <div class="account">
                        <a href="{% url 'profile' %}"><img src="{% static 'profile.png' %}" alt="signin" width="25px" height="25px">Profile</a>
                        <a href="{% url 'settings' %}"><img src="{% static 'settings.png' %}" alt="signin" width="25px" height="25px">Settings</a>
                        <a href="{% url 'signout' %}"><img src="{% static 'signin.png' %}" alt="signin" width="25px" height="25px"> Sign Out</a>
                    </div>
                </details>
            </ul>
        </nav>
    </header>
    
    <main>

        <section class="intro">
            <div class="info">
                <span>Uploaded {{project.created_at | timesince}} ago</span>
                <h1>{{project.title}}</h1>
                <h2>{{project.category}}</h2>

                {% if user in project.likes.all %}
                <h3><a href="{% url 'like' project.id %}" style="color: inherit;">{{project.number_of_likes}} like(s) ❤️</a></h3>
                {% else %}
                <h3><a href="{% url 'like' project.id %}" style="color: inherit;">{{project.number_of_likes}} like(s) 🤍</a></h3>
                {% endif %}
                
                    <h3>
                        <a href="{% url 'profile' project.uploaded_by.id %}">
                        <img src="{% static 'user.png' %}" alt="user-profile" width="30" height="30">{{project.uploaded_by}}
                        </a>
                    </h3>
                <div class="links">
                    <a href="{{project.github_link}}" target="_blank"><img src="{% static 'github.png' %}" alt="github" width="30" height="30">GitHub</a>
                    <a href="{{project.live_link}}" target="_blank"><img src="{% static 'link.png' %}" alt="link" width="30" height="30">Live Link</a>
                </div>
            </div>

            <div class="image">
                <img src="{{project.cover_image.url}}" alt="Project Cover Image">
            </div>
        </section>

        <section class="video-description">
            <video height="600" width="100%" controls>
                <source src="{{project.demo_video.url}}" type="video/mp4">
            </video>
            <div class="description">
                <h2>Project Description</h2>
                <p>{{project.description}}</p>
            </div>

            <form method="POST">
                <h2>Comments</h2>
                {% csrf_token %}
                <div class="comment">
                    {{ comment_form.content }}
                    <button type="submit" name="comment_submit"><img src="{% static 'send.png' %}" alt="send comment" width="28" height="28"></button>
                </div>
            </form>
            <hr>

            {% for comment in comments %}
                <span>
                    <strong>{{ comment.user.username }}</strong>
                    <div class="content">{{ comment.content }}</div>
                    <small>{{ comment.created_at | timesince}} ago</small>

                    <!-- delete comment form -->
                     {% if comment.user == request.user %}
                        <form action="{% url 'delete-comment' comment.id %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="delete" style="margin-bottom: .5rem;">Delete</button>                            
                        </form>
                    {% endif %}
                </span>

                <form method="POST">
                    {% csrf_token %}
                    <div class="reply">
                        {{ reply_form.content }}
                        <input type="hidden" name="comment_id" value="{{ comment.id }}">
                        <button type="submit" name="reply_submit">Reply</button>
                    </div>
                </form>

                {% for reply in comment.reply_set.all %}
                    <span style="margin-left: 1rem; display: block; margin-top: 1rem;">
                        <strong style="margin-left: 20px;">{{ reply.user.username }}</strong>
                        <div class="content" style="margin-left: 20px;">{{ reply.content }}</div>
                        <small style="margin-left: 20px;">{{ reply.created_at | timesince}} ago</small>

                        <!-- delete reply form -->
                     {% if reply.user == request.user %}
                        <form action="{% url 'delete-reply' reply.id %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="delete" style="margin-left: 20px;">Delete</button>                           
                        </form>
                    {% endif %}
                    </span>
                {% endfor %}
                <hr>
            {% endfor %}
        </section>
    </main>

    <footer>
        <div class="scholarRepo footer">
            <img src="{% static 'logo.png' %}" alt="logo" class="nav-img" width="120" height="120">
        </div>
        <div class="footer">
            <ul>
                <h5>Socials</h5>
                <a href="https://www.x.com/">X</a>
                <a href="https://www.instagram.com/">Instagram</a>
                <a href="https://www.facebook.com/">Facebook</a>
                <a href="https://www.linkedin.com/">LinkedIn</a>
            </ul>
        </div>
        <div class="footer">
            <ul>
                <h5>Explore</h5>
                <a href="#">Alerts</a>
                <a href="#">My Account</a>
                <a href="#">Find Repo</a>
                <a href="{% url 'upload' %}">Upload Project</a>
            </ul>
        </div>
        <div class="footer">
            <ul>
                <h5>Developers</h5>
                <a href="https://sbk-socials.vercel.app/"><em>SBKmadeIT</em></a>
                <a href="https://www.facebook.com/">Facebook</a>
                <a href="https://www.snapchat.com/">Snapchat</a>
                <a href="https://www.instagram.com/">Instagram</a>
            </ul>
        </div>
        <div class="footer">
            <ul>
                <h5>Legal</h5>
                <a href="{% url 'legal' %}#terms">Terms</a>
                <a href="{% url 'legal' %}#privacy">Privacy</a>
                <a href="{% url 'legal' %}#licenses">Licenses</a>
                <!-- <a href="{% url 'legal' %}#terms"></a> -->
            </ul>
        </div>
    </footer>
    <p> &copy; <script> document.write(new Date().getFullYear()) </script> SBKmadeIT | All Rights Reserved</p>
</body>
</html>

templates/settings.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/jpg" href="{% static 'favicon.jpg' %}">
    <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'settings.css' %}">
    <title>ScholarRepo | Settings</title>
</head>
<body>
    <header>
        <img src="{% static 'header.png' %}" alt="ScholarRepo" class="img-header">
        <nav>
            <ul>
                <a href="{% url 'home' %}" class="home"><img src="{% static 'home.png' %}" alt="home" width="25px" height="25px" class="nav-img">Home</a>
                <a href="{% url 'find' %}"><img src="{% static 'find.png' %}" alt="find" width="25px" height="25px" class="nav-img">Find</a>
                <a href="{% url 'upload' %}"><img src="{% static 'upload.png' %}" alt="upload" width="25px" height="25px" class="nav-img">Upload</a>
                <a href="#"><img src="{% static 'notification.png' %}" alt="alerts" width="25px" height="25px" class="nav-img">Alerts</a>
                <details>
                    <summary>
                        <img src="{% static 'user.png'%}" alt="user" width="25px" height="25px" class="nav-img">Account
                    </summary>
                    <div class="account">
                        <a href="{% url 'profile' %}"><img src="{% static 'profile.png' %}" alt="signin" width="25px" height="25px">Profile</a>
                        <a href="{% url 'settings'%}"><img src="{% static 'settings.png' %}" alt="signin" width="25px" height="25px">Settings</a>
                        <a href="{% url 'signout' %}"><img src="{% static 'signin.png' %}" alt="signin" width="25px" height="25px"> Sign Out</a>
                    </div>
                </details>
            </ul>
        </nav>
    </header>

    <main>
        <aside>
            <div class="tabs">
                <h1>Settings</h1>
                <h2 class="active"><a href="{% url 'settings' %}">General</a></h2>
                <h2><a href="{% url 'project-settings'%}">Project Settings</a></h2>
                <h2><a href="">Account</a></h2>
                <h2><a href="{% url 'legal' %}">Legal</a></h2>
            </div>
            <div class="account-user">
                <img src="{{user.profile_pic.url}}" alt="user" width="30" height="30" style="border-radius: 50%;">
                <h2>{{user.username}}</h2>
            </div>
        </aside>
        <section>
            <div class="settings-header">
                <h2>General 
                </h2>
                {% if messages %}
                        <ul class="messages">
                    {% for message in messages%}
                        <li class="{{message.tags}}">{{message}}</li>
                        {% endfor %}
                        </ul>
                {% endif %}
            </div>
            <form class="user-info" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="name">
                    <label for="id_profile_pic"><img src="{{user.profile_pic.url}}" alt="profile pic" width="128" height="128">{{form.profile_pic}}</label>
                    <h3>{{form.first_name}} {{form.last_name}}</h3>
                    <div class="socials">
                        <details>
                            <summary>
                                <img src="{% static 'mail.png' %}" alt="mail" width="30" height="30">
                            </summary>
                            {{form.email}}
                        </details>
                        <details>
                            <summary>
                                <img src="{% static 'github.png' %}" alt="github" width="30" height="30">
                            </summary>
                            {{form.github}}
                        </details>
                        <details>
                            <summary>
                                <img src="{% static 'linkedin.png' %}" alt="linkedin" width="30" height="30">
                            </summary>
                            {{form.linkedin}}
                        </details>
                        <details>
                            <summary>
                                <img src="{% static 'instagram.png' %}" alt="insta" width="30" height="30">
                            </summary>
                            {{form.instagram}}
                        </details>
                        <details>
                            <summary>
                                <img src="{% static 'link.png' %}" alt="web" width="30" height="30">
                            </summary>
                            {{form.link}}
                        </details>
                    </div>
                </div>
                <div class="bio">
                    <h3>Bio</h3>
                    {{form.bio}}
                    <button type="submit">Update</button>
                </div>
            </form>
            <div class="theme">
                <h3>Theme</h3>
                <span class="dark">dark</span>
                <span class="light">light</span>
                <span class="system">system</span>
            </div>
        </section>
    </main>
</body>
</html>

templates/signup.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/jpg" href="{% static 'favicon.jpg' %}">
    <title>ScholarRepo | Signup</title>
    <link rel="stylesheet" href="{% static 'signup.css' %}">
</head>
<body>
    <header>
        <img src="{% static 'header.png' %}" alt="ScholarRepo" class="img-header">
        <nav>
            <a href="{% url 'signin' %}"><img src="{% static 'signin.png' %}" alt="signin" width="30px" height="30px">Sign In</a>
        </nav>
    </header>

    <main>
        {% if messages %}
        <ul class="messages">
            {% for message in messages%}
            <li class="{{message.tags}}">{{message}}</li>
            {% endfor %}
        </ul>
        {% endif %}
        <fieldset>
            <legend>Sign Up</legend>
            <form action="" method="POST">
                {% csrf_token %}

                <label for="id_first_name">First Name(s)</label>
                {{form.first_name}}

                <label for="id_last_name">Last Name</label>
                {{form.last_name}}

                <label for="id_email">Email</label>
                {{form.email}}

                <label for="id_username">Username</label>
                {{form.username}}

                <label for="id_password1">Create Password</label>
                {{form.password1}}

                <label for="id_password2">Confirm Password</label>
                {{form.password2}}

                <label for="check" class="check"><input type="checkbox" required name="check">I agree to <a href="#"> Terms </a> of service</label>

                <input type="submit" class="submit">
            </form>
        </fieldset>
    <p> &copy; <script> document.write(new Date().getFullYear()) </script> SBKmadeIT | All Rights Reserved</p>
    </main>
</body>
</html>

templates/upload.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/jpg" href="{% static 'favicon.jpg' %}">
    <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">
    <title>ScholarRepo | Upload</title>
    <link rel="stylesheet" href="{% static 'upload.css' %}">
</head>
<body>
    <header>
        <img src="{% static 'header.png' %}" alt="ScholarRepo" class="img-header">
        <nav>
            <ul>
                <a href="{% url 'home' %}" class="nav-img"><img src="{% static 'home.png' %}" alt="home" width="25px" height="25px">Home</a>
                <a href="{% url 'find' %}"><img src="{% static 'find.png' %}" alt="find" width="25px" height="25px" class="nav-img">Find</a>
                <a href="{% url 'upload' %}" class="upload"><img src="{% static 'upload.png' %}" alt="upload" width="25px" height="25px">Upload</a>
                <a href="#"><img src="{% static 'notification.png' %}" alt="alerts" width="25px" height="25px" class="nav-img">Alerts</a>
                <details>
                    <summary>
                        <img src="{% static 'user.png'%}" alt="user" width="25px" height="25px" class="nav-img">Account
                    </summary>
                    <div class="account">
                        <a href="{% url 'profile' %}"><img src="{% static 'profile.png' %}" alt="signin" width="25px" height="25px">Profile</a>
                        <a href="{% url 'settings'%}"><img src="{% static 'settings.png' %}" alt="signin" width="25px" height="25px">Settings</a>
                        <a href="{% url 'signout' %}"><img src="{% static 'signin.png' %}" alt="signin" width="25px" height="25px"> Sign Out</a>
                    </div>
                </details>
            </ul>
        </nav>
    </header>
    
    <main>
        {% if messages %}
        <ul class="messages">
            {% for message in messages%}
            <li class="{{message.tags}}">{{message}}</li>
            {% endfor %}
        </ul>
        {% endif %}

        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <h2>Upload New Project</h2>

            <label for="id_category">Project Category</label>
            {{form.category}}

            <label for="id_title">Project Name</label>
            {{form.title}}

            <label for="id_description">Description</label>
            {{form.description}}

            <div class="link">
                <div class="link-content">
                    <label for="id_live_link">Live Link</label>
                    {{form.live_link}}
                </div>
                <div class="link-content">
                    <label for="id_github_link">GitHub Link</label>
                    {{form.github_link}}
                </div>            
            </div>

            <div class="file">
                <div class="file-content">
                    <label for="id_cover_image"><img src="{% static 'cloud.png' %}" alt="cloud" width="30" height="30">Cover Image</label>
                    {{form.cover_image}}
                </div>
    
                <div class="file-content">
                    <label for="id_demo_video"><img src="{% static 'cloud.png' %}" alt="cloud" width="30" height="30">Demo Video</label>
                    {{form.demo_video}}
                </div>
            </div>

            <button type="submit" class="submit">Submit</submit>

        </form>
    </main>

    <footer>
        <div class="scholarRepo footer">
            <img src="{% static 'logo.png' %}" alt="logo" class="nav-img" width="120" height="120">
        </div>
        <div class="footer">
            <ul>
                <h5>Socials</h5>
                <a href="https://www.x.com/">X</a>
                <a href="https://www.instagram.com/">Instagram</a>
                <a href="https://www.facebook.com/">Facebook</a>
                <a href="https://www.linkedin.com/">LinkedIn</a>
            </ul>
        </div>
        <div class="footer">
            <ul>
                <h5>Explore</h5>
                <a href="#">Alerts</a>
                <a href="#">My Account</a>
                <a href="#">Find Repo</a>
                <a href="{% url 'upload' %}">Upload Project</a>
            </ul>
        </div>
        <div class="footer">
            <ul>
                <h5>Developers</h5>
                <a href="https://sbk-socials.vercel.app/"><em>SBKmadeIT</em></a>
                <a href="https://www.facebook.com/">Facebook</a>
                <a href="https://www.snapchat.com/">Snapchat</a>
                <a href="https://www.instagram.com/">Instagram</a>
            </ul>
        </div>
        <div class="footer">
            <ul>
                <h5>Legal</h5>
                <a href="{% url 'legal' %}#terms">Terms</a>
                <a href="{% url 'legal' %}#privacy">Privacy</a>
                <a href="{% url 'legal' %}#licenses">Licenses</a>
                <!-- <a href="{% url 'legal' %}#terms"></a> -->
            </ul>
        </div>
    </footer>

   <p class="right"> &copy; <script> document.write(new Date().getFullYear()) </script> SBKmadeIT | All Rights Reserved</p> 
</body>
</html>